AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates EC2 instance with an SSH connection.


Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
     
      ImageId: ami-0533f2ba8a1995cf9
 
      InstanceType: t2.micro
   
      KeyName: Firstkey
     
      SecurityGroups:
        - cfn-sec-group
     
      Tags:
        - Key: Name
          Value: cfn-instance
      
