AWSTemplateFormatVersion: 2010-09-09

  
Resources: 
  LogicalID:
    Type: AWS::EC2::Instance
    Properties:
    
      ImageId: ami-0742b4e673072066f
    
      InstanceType: t2.micro
    
      KeyName: Firstkey
    
      SecurityGroups:
        - FirstSG
    
      Tags:
        - Key: Name
          Value: First-Project
    
      UserData: 
        Fn::Base64:
          !Sub | 
            #! /bin/bash
     
            yum update -y
      
            yum install -y httpd


            systemctl start httpd
            systemctl enable httpd

            chmod -R 777/var/www/html


            cd /var/www/html

            wget https://raw.githubusercontent.com/kmlhtpgl/aws-devops/main/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html

            wget https://raw.githubusercontent.com/kmlhtpgl/aws-devops/main/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg      

            wget https://raw.githubusercontent.com/kmlhtpgl/aws-devops/main/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg

            wget https://raw.githubusercontent.com/kmlhtpgl/aws-devops/main/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
 